// <auto-generated />
using System;
using BitcoinAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitcoinAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123163229_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitcoinAPI.Models.BtcRateData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RateEUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateEUR_CZK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RateUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("BtcRateData");
                });
#pragma warning restore 612, 618
        }
    }
}
